# config.yaml
api_keys:
  openai: "sk-your_openai_api_key_from_yaml_if_not_in_env" # Env var takes precedence， If the apikey is not set, the service will start in `no-configured apikey mode`, where user requests need to provide the apikey through `Bear Token` in the request header.

paths:
  data_dir: "/custom/data/path" # Overrides default

embedding:
  model_name: "text-embedding-3-small"
  dimensions: 384

generator:
  model_name: "gpt-4o" # Example

tree_sitter:
  languages:
    python:
      extensions: [".py", ".pyw"]
      grammar_name: "python"
    # java:
    #   extensions: [".java"]
    #   grammar_file: "java.so" # If manually managing compiled grammars in GRAMMAR_DIR
    #   language_name_in_lib: "java"
  ast_chunk_max_tokens: 800

retrieval:
  vector_top_k: 20
  bm25_top_k: 5